apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-app-deployment-jenkis
spec:
  selector:
   matchLabels:
    app: time-app-jenkis
  replicas: 2
  template:
    metadata:
      labels:
        app: time-app-jenkis
    spec:
      containers:
        - name: time-app-jenkis
          image: jiflorez/timeappchallenge       
          ports:
            - containerPort: 80
              name: timeapp
---
apiVersion: v1
kind: Service
metadata:
  name: time-app-service-jenkis
  labels:
    app: time-app-jenkis
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3002
      name: time-app-jenkis
  selector:
    app: time-app-jenkins
